version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
       - 3306:3306
    networks:
       - network
    environment:
      MYSQL_DATABASE: eclinic
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 654321
      MYSQL_PASSWORD: 654321
    restart: always
    
  clinic-management-system:
    build: .
    restart: always
    ports:
      - 8080:8080
    # environment:
    #   - spring.datasource.url=jdbc:mysql://localhost:3306/eclinic?useSSL=false&serverTimezone=UTC
    #   - spring.datasource.username=root
    #   - spring.datasource.password=654321
    networks:
      - network
    depends_on:
      - mysql
networks:
  network: